version: '3'

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        ports:
            - 443:443
        volumes:
            - wordpress_data:/var/www/html
        restart: always
        networks:
            - network
        env_file:
            - .env

    mariadb:
        container_name: mariadb
        networks:
            - network
        build: ./requirements/mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        restart: always
        env_file:
            - .env

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build:	
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - wordpress_data:/var/www/html
        restart: always
        networks:
            - network
        env_file:
            - .env

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/nmascrie/data/mysql
            o: bind
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/nmascrie/data/wordpress
            o: bind

networks:
    network:
        driver: bridge
